### PR TITLE
moved styles to componentDidMount in order to support isomorphic application support

### PR DESCRIPTION
**Pull request by yury-dymov**

### CODE REVIEW

**Comment by vahnag** [comment]
Thanks Yury for this PR, though I'd like to discuss a couple things before merging.

* Won't moving loading styles until the component is mounted render the component without styles initially?
* Why fit the timezones list for Rails? Those timezones are perfectly valid in `moment.js`.

**Comment by yury-dymov** [comment]
Hi vahnag,

1) removing locales commit was not intended to be part of PR. So please ignore it. It was done for my private purposes. 

2) Most of the projects are using webpack-extract-plugin to build one big css for website anyway to leverage caching.  It is loaded initially and therefore your component will be with styles as they are applied via className. At the same time applications with server-side rendering might face an issue with importing styles via 'import'.

Kind regards,
Yuri.

**Comment by vahnag** [comment]
Why not use something like [this](https://github.com/bkonkle/ignore-styles) to ignore styles on server then?

IMHO including styles on top is much more declarative than in `componentDidMount` hook.

**Comment by yury-dymov** [comment]
Make sense. Sorry for bothering than :)

**Comment by vahnag** [comment]
No problem!

**Pull request closed without merging**
